---
- name: Install Latex for FreeBSD
  become: true
  community.general.pkgng:
    name: texlive-full
  tags:
    - install
  when: ansible_facts.system == "FreeBSD"

- name: Install Latex for Linux
  ansible.builtin.package:
    name: >-
      {{ 'texlive-bin' if system_pkg_mgr == 'pacman' else 'texlive' }}
  become: true
  tags:
    - install
  when: ansible_facts.system == "Linux"

- name: Install Latex for MacOS
  become: true
  become_user: "{{ brew_user }}"
  community.general.homebrew:
    name: texlive
  tags:
    - install
  when: ansible_facts.system == "Darwin"

- name: Install Latex for Windows
  community.windows.win_scoop:
    global: true
    name: miktex
  tags:
    - install
  when: ansible_facts.system == "Win32NT"
