---
- name: Install Ripgrep for FreeBSD
  become: true
  community.general.pkgng:
    name: ripgrep
  when: ansible_system == "FreeBSD"

- name: Install Ripgrep for Linux
  ansible.builtin.package:
    name: ripgrep
    state: present
  become: true
  when: ansible_system == "Linux"

- name: Install Ripgrep for MacOS
  become: true
  become_user: "{{ user_id }}"
  community.general.homebrew:
    name: ripgrep
  when: ansible_system == "Darwin"

- name: Install Ripgrep for Windows
  community.windows.win_scoop:
    name: ripgrep
  when: ansible_system == "Win32NT"
