---
- name: Create Alacritty temporary directory for MacOS
  ansible.builtin.tempfile:
    state: directory
  register: alacritty_temp
  tags:
    - install
  when: ansible_facts.system == "Darwin"

- name: Set Alacritty temporary directory permissions for MacOS
  ansible.builtin.file:
    mode: "755"
    path: "{{ alacritty_temp.path }}"
    state: directory
  tags:
    - install
  when: ansible_facts.system == "Darwin"

- name: Get latest Alacritty version for MacOS
  ansible.builtin.uri:
    headers: "{{ github_api_headers }}"
    method: GET
    return_content: true
    url: https://api.github.com/repos/alacritty/alacritty/releases/latest
  register: alacritty_release
  tags:
    - install
  when: ansible_facts.system == "Darwin"

- name: Install Alacritty for FreeBSD
  become: true
  community.general.pkgng:
    name: alacritty
  tags:
    - install
  when:
    - system_install
    - ansible_facts.system == "FreeBSD"

- name: Install Alacritty for Linux
  ansible.builtin.package:
    name: alacritty
  become: true
  tags:
    - install
  when:
    - system_install
    - ansible_facts.system == "Linux"

- name: Download Alacritty for MacOS
  ansible.builtin.get_url:
    dest: "{{ alacritty_temp.path }}/alacritty.dmg"
    mode: "644"
    url: >-
      https://github.com/alacritty/alacritty/releases/download/{{
      alacritty_release.json.tag_name }}/Alacritty-{{
      alacritty_release.json.tag_name }}.dmg
  tags:
    - install
  when: ansible_facts.system == "Darwin"

- name: Mount Alacritty disk image for MacOS
  ansible.builtin.command:
    cmd: >-
      hdiutil attach -nobrowse -quiet -mountpoint {{ alacritty_temp.path
      }}/alacritty {{ alacritty_temp.path }}/alacritty.dmg
  changed_when: true
  tags:
    - install
  when: ansible_facts.system == "Darwin"

- name: Install Alacritty for MacOS
  ansible.builtin.copy:
    dest: >-
      {{ '/Applications/' if system_install else user_home + '/Applications/' }}
    mode: "755"
    force: true
    remote_src: true
    src: "{{ alacritty_temp.path }}/alacritty/Alacritty.app"
  become: "{{ system_install }}"
  tags:
    - install
  when: ansible_facts.system == "Darwin"

- name: Unmount Alacritty disk image for MacOS
  ansible.builtin.command:
    cmd: hdiutil detach -quiet {{ alacritty_temp.path }}/alacritty
  changed_when: true
  tags:
    - install
  when: ansible_facts.system == "Darwin"

- name: Make Alacritty symlink for MacOS
  ansible.builtin.file:
    src: >-
      {{ '/Applications' if system_install else user_home + '/Applications'
      }}/Alacritty.app/Contents/MacOS/alacritty
    dest: "{{ bin_path }}/alacritty"
    force: true
    mode: "755"
    state: link
  become: "{{ system_install }}"
  tags:
    - install
  when: ansible_facts.system == "Darwin"

- name: Install Alacritty for Windows
  community.windows.win_scoop:
    global: "{{ system_install }}"
    name: alacritty
  tags:
    - install
  when: ansible_facts.system == "Win32NT"

- name: Create Alacritty configuration directory for Unix
  ansible.builtin.file:
    group: "{{ group_id if system_install else omit }}"
    mode: "755"
    owner: "{{ user_id if system_install else omit }}"
    path: "{{ user_home }}/.config/alacritty"
    state: directory
  become: "{{ system_install }}"
  tags:
    - config
  when: ansible_facts.system != "Win32NT"

- name: Create Alacritty configuration directory for Windows
  ansible.windows.win_file:
    path: "{{ user_home }}\\AppData\\Roaming\\alacritty"
    state: directory
  tags:
    - config
  when: ansible_facts.system == "Win32NT"

- name: Copy Alacritty configuration file for Unix
  ansible.builtin.template:
    dest: "{{ user_home }}/.config/alacritty/alacritty.toml"
    force: true
    group: "{{ group_id if system_install else omit }}"
    mode: "644"
    owner: "{{ user_id if system_install else omit }}"
    src: alacritty.toml.j2
  become: "{{ system_install }}"
  tags:
    - config
  when: ansible_facts.system != "Win32NT"

- name: Copy Alacritty configuration file for Windows
  ansible.windows.win_template:
    dest: "{{ user_home }}\\AppData\\Roaming\\alacritty\\alacritty.toml"
    force: true
    src: alacritty.toml.j2
  tags:
    - config
  when: ansible_facts.system == "Win32NT"

- name: Set owner of Alacritty files for Windows
  ansible.windows.win_owner:
    path: "{{ user_home }}\\AppData\\Roaming\\alacritty"
    recurse: true
    user: "{{ user_id }}"
  tags:
    - config
  when: ansible_facts.system == "Win32NT"

- name: Remove Alacritty temporary directory for MacOS
  ansible.builtin.file:
    path: "{{ alacritty_temp.path }}"
    state: absent
  tags:
    - install
  when: ansible_facts.system == "Darwin"
