---
- name: Install GitLab Runner for Alpine
  become: true
  community.general.apk:
    name: gitlab-runner
  tags:
    - install
  when: system_pkg_mgr == "apk"

- name: Install GitLab Runner for Arch
  become: true
  community.general.pacman:
    name: gitlab-runner
  tags:
    - install
  when: system_pkg_mgr == "pacman" and system_architecture == "amd64"

- name: Check if GitLab Runner is installed for Linux
  ansible.builtin.stat:
    path: "{{ gitlab_runner_path[system_pkg_mgr] }}"
  register: gitlab_runner_stat
  tags:
    - install
  vars:
    gitlab_runner_path:
      apt: /usr/bin/gitlab-runner
      dnf: /usr/sbin/gitlab-runner
      zypper: /usr/sbin/gitlab-runner
  when: system_pkg_mgr in ["apt", "dnf", "zypper"]

- name: Create GitLab Runner temporary directory for Linux
  ansible.builtin.tempfile:
    state: directory
  register: gitlab_runner_temp
  tags:
    - install
  when: >-
    system_pkg_mgr in ["apt", "dnf", "zypper"] and not
    gitlab_runner_stat.stat.exists

- name: Set GitLab Runner temporary directory permissions for Linux
  ansible.builtin.file:
    mode: "755"
    path: "{{ gitlab_runner_temp.path }}"
    state: directory
  tags:
    - install
  when: >-
    system_pkg_mgr in ["apt", "dnf", "zypper"] and not
    gitlab_runner_stat.stat.exists

- name: Download GitLab Runner setup script for Linux
  ansible.builtin.get_url:
    dest: "{{ gitlab_runner_temp.path }}/script.sh"
    mode: "755"
    url: >-
      https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.{{
      gitlab_runner_pkg[system_pkg_mgr] }}.sh
  tags:
    - install
  vars:
    gitlab_runner_pkg:
      apt: deb
      dnf: rpm
      zypper: rpm
  when: >-
    system_pkg_mgr in ["apt", "dnf", "zypper"] and not
    gitlab_runner_stat.stat.exists

- name: Run GitLab Runner setup script for Linux
  ansible.builtin.command:
    cmd: "{{ gitlab_runner_temp.path }}/script.sh"
  become: true
  changed_when: "'Nothing to do' not in gitlab_runner_setup.stdout"
  register: gitlab_runner_setup
  tags:
    - install
  when: >-
    system_pkg_mgr in ["apt", "dnf", "zypper"] and not
    gitlab_runner_stat.stat.exists

- name: Install GitLab Runner for Debian
  ansible.builtin.apt:
    name: gitlab-runner
  become: true
  tags:
    - install
  when: system_pkg_mgr == "apt"

- name: Install GitLab Runner for Fedora
  ansible.builtin.dnf:
    name: gitlab-runner
  become: true
  tags:
    - install
  when: system_pkg_mgr == "dnf"

- name: Install GitLab Runner for FreeBSD
  become: true
  community.general.pkgng:
    name: gitlab-runner
  tags:
    - install
  when: ansible_facts.system == "FreeBSD"

- name: Install GitLab Runner for MacOS
  become: true
  become_user: "{{ brew_user }}"
  community.general.homebrew:
    name: gitlab-runner
  tags:
    - install
  when: ansible_facts.system == "Darwin"

- name: Install GitLab Runner for Suse
  become: true
  community.general.zypper:
    name: gitlab-runner
  tags:
    - install
  when: system_pkg_mgr == "zypper"

- name: Install GitLab Runner for Windows
  community.windows.win_scoop:
    global: true
    name: gitlab-runner
  tags:
    - install
  when: ansible_facts.system == "Win32NT"

- name: Get all groups for Unix
  ansible.builtin.getent:
    database: group
    split: ":"
  become: true
  tags:
    - install
  when: ansible_facts.system in ["FreeBSD", "Linux"]

- name: Configure GitLab runner user for MacOS
  ansible.builtin.user:
    append: true
    groups:
      - wheel
    name: gitlab-runner
    shell: /bin/bash
  become: true
  tags:
    - install
  when: ansible_facts.system == "Darwin"

- name: Configure GitLab runner user for Unix
  ansible.builtin.user:
    append: true
    groups: >-
      {{ ['docker', 'wheel'] | intersect(ansible_facts.getent_group.keys()) }}
    name: gitlab-runner
    shell: /bin/bash
  become: true
  tags:
    - install
  when: ansible_facts.system in ["FreeBSD", "Linux"]

- name: Check if Doas is available for Unix
  ansible.builtin.shell: command -v doas # noqa command-instead-of-shell
  changed_when: false
  failed_when: false
  register: gitlab_runner_doas_available
  tags:
    - install
  when: ansible_facts.system != "Win32NT"

- name: Enable GitLab passwordless doas for Unix
  ansible.builtin.blockinfile:
    block: |
      # Enable passwordless doas for gitlab-runner user.
      permit nopass gitlab-runner
    create: true
    marker: >-
      # {mark} ANSIBLE MANAGED passwordless doas for gitlab-runner BLOCK
    mode: "400"
    path: /etc/doas.d/doas.conf
    validate: doas -C %s
  become: true
  tags:
    - install
  when: >-
    ansible_facts.system != "Win32NT" and gitlab_runner_doas_available.rc == 0

- name: Check if Sudo is available for Unix
  ansible.builtin.shell: command -v visudo # noqa command-instead-of-shell
  changed_when: false
  failed_when: false
  register: gitlab_runner_sudo_available
  tags:
    - install
  when: ansible_facts.system != "Win32NT"

- name: Enable GitLab Runner passwordless sudo for Unix
  ansible.builtin.blockinfile:
    block: |
      # Enable passwordless sudo for gitlab-runner user.
      gitlab-runner ALL=(ALL) NOPASSWD:ALL
    create: true
    marker: "# {mark} ANSIBLE MANAGED passwordless sudo for gitlab-runner BLOCK"
    # File needs to have 440 permissions as explained at
    # https://wiki.archlinux.org/title/sudo#Sudoers_default_file_permissions.
    mode: "440"
    path: /etc/sudoers
    validate: visudo --check --file %s
  become: true
  tags:
    - install
  when: >-
    ansible_facts.system != "Win32NT" and gitlab_runner_sudo_available.rc == 0

- name: Remove GitLab Runner temporary directory for Linux
  ansible.builtin.file:
    path: "{{ gitlab_runner_temp.path }}"
    state: absent
  tags:
    - install
  when: >-
    system_pkg_mgr in ["apt", "dnf", "zypper"] and not
    gitlab_runner_stat.stat.exists
