---
# TODO: Integrate once installation becomes stable.
# - name: Install Google Chrome for Alpine
#   become: true
#   community.general.apk:
#     name: chromium
#     repository: http://dl-cdn.alpinelinux.org/alpine/edge/community
#     state: latest
#     update_cache: true
#   tags:
#     - install
#   when: system_pkg_mgr == "apk"

- name: Install Google Chrome for Arch
  become: true
  community.general.pacman:
    name: chromium
  tags:
    - install
  when: system_pkg_mgr == "pacman"

- name: Install Google Chrome for Debian
  ansible.builtin.apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  become: true
  tags:
    - install
  when: system_pkg_mgr == "apt" and system_architecture == "amd64"

- name: Add Google GPG key for Fedora
  ansible.builtin.rpm_key:
    key: https://dl.google.com/linux/linux_signing_key.pub
  become: true
  tags:
    - install
  when: >-
    system_pkg_mgr in ["dnf", "zypper"] and system_architecture == "amd64"

- name: Install Google Chrome for Fedora
  ansible.builtin.dnf:
    name: >-
      https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
  become: true
  tags:
    - install
  when: >-
    system_pkg_mgr == "dnf" and system_architecture == "amd64"

- name: Install Google Chrome for FreeBSD
  become: true
  community.general.pkgng:
    name: chromium
  tags:
    - install
  when: ansible_facts.system == "FreeBSD"

- name: Install Google Chrome for MacOS
  community.general.homebrew_cask:
    accept_external_apps: true
    name: google-chrome
    state: present
  tags:
    - install
  when: ansible_facts.system == "Darwin"

- name: Install Google Chrome for Windows
  community.windows.win_scoop:
    global: true
    name: googlechrome
  tags:
    - install
  when: ansible_facts.system == "Win32NT"

# Service directory must be created before file operations.
- name: Create Google Chrome services directories for Unix
  ansible.builtin.file:
    mode: "700"
    path: "{{ item | dirname }}"
    state: directory
  become: true
  loop: "{{ chrome_services }}"
  tags:
    - install
  when: ansible_facts.system != "Win32NT"

# Services need to be removed before they can be blocked since Ansible cannot
# directly replace one file type with another, i.e. directory to file.
- name: Remove Google Chrome services for Unix
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  become: true
  loop: "{{ chrome_services }}"
  tags:
    - install
  when: ansible_facts.system != "Win32NT"

- name: Block Google Chrome services for Unix
  ansible.builtin.file:
    group: nogroup
    mode: "000"
    owner: nobody
    path: "{{ item }}"
    state: touch
  become: true
  loop: "{{ chrome_services }}"
  tags:
    - install
  when: ansible_facts.system != "Win32NT"

# Chrome features are documented at https://chromeenterprise.google/policies.
- name: Set Google Chrome features for MacOS
  ansible.builtin.script: macos.sh
  become: true
  become_user: "{{ user_id }}"
  tags:
    - config
  when: ansible_facts.system == "Darwin"

- name: Create Google Chrome preferences directories for Unix
  ansible.builtin.file:
    mode: "755"
    path: /etc/opt/chrome/policies/managed
    state: directory
  become: true
  tags:
    - config
  when: ansible_facts.system not in ["Darwin", "Win32NT"]

- name: Set Google Chrome features for Unix
  ansible.builtin.get_url:
    dest: /etc/opt/chrome/policies/managed/managed_policies.json
    mode: "644"
    url: https://raw.githubusercontent.com/corbindavenport/just-the-browser/refs/heads/main/chrome/managed_policies.json
  become: true
  tags:
    - config
  when: ansible_facts.system not in ["Darwin", "Win32NT"]

- name: Set Google Chrome features for Windows
  ansible.windows.win_regedit:
    data: "{{ item.data }}"
    name: "{{ item.name }}"
    path: HKLM:\SOFTWARE\Policies\Google\Chrome
    type: dword
  loop:
    - data: 1
      name: AIModeSettings
    - data: 2
      name: CreateThemesSettings
    - data: 2
      name: DevToolsGenAiSettings
    - data: 2
      name: HelpMeWriteSettings
    - data: 1
      name: GeminiSettings
    - data: 1
      name: GenAILocalFoundationalModelSettings
    - data: 2
      name: HistorySearchSettings
    - data: 2
      name: TabCompareSettings
  tags:
    - config
  when: ansible_facts.system == "Win32NT"
