---
- name: Remove Google Chrome services for MacOS
  ansible.builtin.file:
    path: "{{ path }}"
    state: absent
  become: true

- name: Block Google Chrome services for MacOS
  ansible.builtin.file:
    group: nogroup
    mode: "000"
    owner: nobody
    path: "{{ path }}"
    state: directory
  become: true
