---
- name: Install Tailscale for FreeBSD
  become: true
  community.general.pkgng:
    name: tailscale
  tags:
    - install
  when:
    - system_install
    - ansible_facts.system == "FreeBSD"

- name: Install Tailscale for Linux
  ansible.builtin.shell: # noqa command-instead-of-module
    cmd: curl -LSfs https://tailscale.com/install.sh | sh
    creates: /usr/bin/tailscale
  become: true
  tags:
    - install
  when:
    - system_install
    - ansible_facts.system == "Linux"
    - systemd

- name: Install Tailscale for MacOS
  become: "{{ system_install }}"
  become_user: "{{ brew_user if system_install else omit }}"
  community.general.homebrew:
    name: tailscale
  tags:
    - install
  when: ansible_facts.system == "Darwin"

- name: Install Tailscale for Windows
  community.windows.win_scoop:
    global: "{{ system_install }}"
    name: tailscale
  tags:
    - install
  when: ansible_facts.system == "Win32NT"
