---
- name: Install RClone for FreeBSD
  become: true
  community.general.pkgng:
    name: rclone
  tags:
    - install
  when:
    - system_install
    - ansible_facts.system == "FreeBSD"

- name: Install RClone for Linux
  ansible.builtin.package:
    name: rclone
    state: present
  become: true
  tags:
    - install
  when:
    - system_install
    - ansible_facts.system == "Linux"

- name: Install RClone for MacOS
  become: "{{ system_install }}"
  become_user: "{{ brew_user if system_install else omit }}"
  community.general.homebrew:
    name: rclone
  tags:
    - install
  when: ansible_facts.system == "Darwin"

- name: Install RClone for Windows
  community.windows.win_scoop:
    global: "{{ system_install }}"
    name: rclone
  tags:
    - install
  when: ansible_facts.system == "Win32NT"

- name: Override Scoop custom Rclone configuration for Windows
  ansible.windows.win_environment:
    level: user
    name: RCLONE_CONFIG
    value: "{{ user_home }}\\AppData\\Roaming\\rclone\\rclone.conf"
  tags:
    - install
  when: ansible_facts.system == "Win32NT"
