---
- name: Create system applications directory for Linux
  ansible.builtin.file:
    dest: /usr/local/share/applications
    mode: "755"
    state: directory
  become: true
  tags:
    - install
  when:
    - system_install
    - ansible_facts.system == "Linux"

- name: Create system binaries directory for Unix
  ansible.builtin.file:
    dest: "{{ bin_path_sys }}"
    mode: "755"
    state: directory
  become: true
  tags:
    - install
  when:
    - system_install
    - ansible_facts.system != "Win32NT"

- name: Create user binaries directory for Unix
  ansible.builtin.file:
    dest: "{{ bin_path_usr }}"
    group: "{{ group_id }}"
    mode: "755"
    owner: "{{ user_id }}"
    state: directory
  become: "{{ system_install }}"
  tags:
    - install
  when: ansible_facts.system != "Win32NT"

- name: Create system profile configuration directory for Unix
  ansible.builtin.file:
    dest: /etc/profile.d
    mode: "755"
    state: directory
  become: true
  tags:
    - install
  when:
    - system_install
    - ansible_facts.system != "Win32NT"
    - system_paths | length > 0

- name: Add binaries directories to system profile for Unix
  ansible.builtin.template:
    dest: /etc/profile.d/bootware.sh
    force: true
    mode: "644"
    src: profile.sh.j2
  become: true
  tags:
    - install
  when:
    - system_install
    - ansible_facts.system != "Win32NT"
    - system_paths | length > 0

- name: Create system environment configuration directory for Linux
  ansible.builtin.file:
    dest: /etc/environment.d
    mode: "755"
    state: directory
  become: true
  tags:
    - install
  when:
    - system_install
    - ansible_facts.system == "Linux"
    - system_paths | length > 0

- name: Add binaries directories to system environment for Linux
  ansible.builtin.template:
    dest: /etc/environment.d/bootware.conf
    force: true
    mode: "644"
    src: environ.conf.j2
  become: true
  tags:
    - install
  when:
    - system_install
    - ansible_facts.system == "Linux"
    - system_paths | length > 0

- name: Create Launchd configuration directory for MacOS
  ansible.builtin.file:
    dest: /private/var/db/com.apple.xpc.launchd/config
    mode: "755"
    state: directory
  become: true
  tags:
    - install
  when:
    - ansible_facts.system == "Darwin"
    - system_paths | length > 0

- name: Add binaries directories to Launchd paths for MacOS
  ansible.builtin.template:
    dest: /private/var/db/com.apple.xpc.launchd/config/user.plist
    force: true
    mode: "644"
    src: user.plist.j2
  become: true
  tags:
    - install
  when:
    - ansible_facts.system == "Darwin"
    - system_paths | length > 0

- name: Create system binaries directory for Windows
  ansible.windows.win_file:
    path: "{{ bin_path_sys }}"
    state: directory
  tags:
    - install
  when: ansible_facts.system == "Win32NT"

- name: Create user binaries directories for Windows
  ansible.windows.win_file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ user_home }}\\.local\\bin"
    - "{{ bin_path_usr }}"
  tags:
    - install
  when: ansible_facts.system == "Win32NT"

- name: Set owner of user binaries directories for Windows
  ansible.windows.win_owner:
    path: "{{ item }}"
    recurse: true
    user: "{{ user_id }}"
  loop:
    - "{{ user_home }}\\.local\\bin"
    - "{{ bin_path_usr }}"
  tags:
    - install
  when: ansible_facts.system == "Win32NT"

- name: Add system binaries directory to path for Windows
  ansible.windows.win_path:
    elements: "{{ bin_path_sys }}"
    scope: machine
  tags:
    - install
  when: ansible_facts.system == "Win32NT"

- name: Add user binaries directories to path for Windows
  ansible.windows.win_path:
    elements: "{{ item }}"
    scope: user
  loop:
    - "{{ user_home }}\\.local\\bin"
    - "{{ bin_path_usr }}"
  tags:
    - install
  when: ansible_facts.system == "Win32NT"

- name: Create user configuration directory for Unix
  ansible.builtin.file:
    dest: "{{ user_home }}/.config"
    group: "{{ group_id }}"
    mode: "755"
    owner: "{{ user_id }}"
    state: directory
  become: "{{ system_install }}"
  tags:
    - install
  when: ansible_facts.system != "Win32NT"

- name: Create user configuration directory for Windows
  ansible.windows.win_file:
    path: "{{ user_home }}\\.config"
    state: directory
  tags:
    - install
  when: ansible_facts.system == "Win32NT"

- name: Set owner of user configuration directory for Windows
  ansible.windows.win_owner:
    path: "{{ user_home }}\\.config"
    recurse: true
    user: "{{ user_id }}"
  tags:
    - install
  when: ansible_facts.system == "Win32NT"

- name: Create system shell completion directories for Unix
  ansible.builtin.file:
    mode: "755"
    path: "{{ item }}"
    state: directory
  become: true
  loop:
    - "{{ bash_completion_sys }}"
    - "{{ fish_completion_sys }}"
    - "{{ nushell_autoload_sys }}"
  tags:
    - completion
    - install
  when:
    - system_install
    - ansible_facts.system != "Win32NT"

- name: Create user shell completion directories for Unix
  ansible.builtin.file:
    group: "{{ group_id }}"
    mode: "755"
    owner: "{{ user_id }}"
    path: "{{ item }}"
    state: directory
  become: "{{ system_install }}"
  loop:
    - "{{ bash_completion_usr }}"
    - "{{ fish_completion_usr }}"
    - "{{ nushell_autoload_usr }}"
  tags:
    - completion
    - install
  when:
    - ansible_facts.system != "Win32NT"
    - user_id != "root"

- name: Create system shell completion directories for Windows
  ansible.windows.win_file:
    path: "{{ item }}"
    state: directory
  loop: "{{ [nushell_autoload_sys] + powershell_module_sys }}"
  tags:
    - completion
    - install
  when: ansible_facts.system == "Win32NT"

- name: Create user shell completion directories for Windows
  ansible.windows.win_file:
    path: "{{ item }}"
    state: directory
  loop: "{{ [nushell_autoload_user] + powershell_module_user }}"
  tags:
    - completion
    - install
  when: ansible_facts.system == "Win32NT"

- name: Set owner of user shell completion directories for Windows
  ansible.windows.win_owner:
    path: "{{ item }}"
    recurse: true
    user: "{{ user_id }}"
  loop: "{{ [nushell_autoload_user] + powershell_module_user }}"
  tags:
    - install
  when: ansible_facts.system == "Win32NT"

- name: Mark role as executed to prevent reruns
  ansible.builtin.set_fact:
    cacheable: true
    path_role_executed: true
