FROM fedora:33 AS builder


# Update DNF package lists.
RUN dnf check-update || { rc=$?; [ "$rc" -eq 100 ] && exit 0; exit "$rc"; }

RUN dnf install -y nodejs rpm-build

# # Copy bootware package build files.
COPY scripts/ /bootware/scripts/
COPY bootware.1 /bootware/
COPY bootware.sh /bootware/
COPY package.json /bootware/

WORKDIR /bootware
RUN npm install

# Build Debian package.
RUN node scripts/build_package.js rpm 0.2.3


FROM fedora:33


# Update DNF package lists.
RUN dnf check-update || { rc=$?; [ "$rc" -eq 100 ] && exit 0; exit "$rc"; }

# Pull Fedora package from previous Docker stage.
COPY --from=builder /bootware/dist/bootware-0.2.3-1.fc33.noarch.rpm /tmp/

# Install Fedora package.
RUN dnf install -y /tmp/bootware-0.2.3-1.fc33.noarch.rpm

# Test package was installed successfully.
RUN bootware --help
