FROM node:14.16.0 AS builder

# Copy bootware package build files.
COPY dist/ /build/dist/
COPY scripts/ /build/scripts/
COPY package.json /build/
COPY bootware.sh /build/

WORKDIR /build
RUN npm install

# Build Debian package.
RUN node scripts/package_debian.js 0.2.1


FROM ubuntu:20.10

# Update Apt package cache.
RUN apt-get update

# Pull Debian package from previous Docker stage.
COPY --from=builder /build/tmp/bootware_0.2.1_all.deb /tmp/

# Install Debian package.
RUN apt-get install -y /tmp/bootware_0.2.1_all.deb

# Test package was installed successfully.
RUN bootware --help
