FROM ubuntu:20.10


# Create non-priviledged user.
#
# Flags:
#     -l: Do not add user to lastlog database.
#     -m: Create user home directory if it does not exist.
#     -s /usr/bin/fish: Set user login shell to Fish.
#     -u 1000: Give new user UID value 1000.
RUN useradd -lm -s /bin/bash -u 1000 debian

# Install Bash, Curl and Sudo.
#
# Flags:
#     -m: Ignore missing packages and handle result.
#     -q: Produce log suitable output by omitting progress indicators.
#     -y: Assume "yes" as answer to all prompts and run non-interactively.
RUN apt-get update -m && apt-get install -qy bash curl sudo

# Add standard user to sudoers group.
RUN usermod -a -G sudo debian

# Allow sudo commands with no password.
RUN printf "%%sudo ALL=(ALL) NOPASSWD:ALL\n" >> /etc/sudoers

# Fix current sudo bug for containers.
# https://github.com/sudo-project/sudo/issues/42
RUN echo "Set disable_coredump false" >> /etc/sudo.conf

ENV USER=debian
USER debian

# Install Bootware.
RUN curl -LSfs https://raw.githubusercontent.com/wolfgangwazzlestrauss/bootware/master/install.sh | bash

# Generate default Bootware configuration file.
RUN bootware config --empty

# Install dependencies for Bootware.
RUN bootware setup

# Run Bootware bootstrapping.
RUN bootware bootstrap --no-passwd
