FROM ubuntu:21.04

ARG TARGETARCH


# Create non-priviledged user.
#
# Flags:
#     -l: Do not add user to lastlog database.
#     -m: Create user home directory if it does not exist.
#     -s /usr/bin/fish: Set user login shell to Fish.
#     -u 1000: Give new user UID value 1000.
RUN useradd -lm -s /bin/bash -u 1000 ubuntu

# Install Bash, Curl, and Sudo.
#
# Flags:
#     -m: Ignore missing packages and handle result.
#     -q: Produce log suitable output by omitting progress indicators.
#     -y: Assume "yes" as answer to all prompts and run non-interactively.
RUN apt-get update -m && apt-get install -qy bash curl sudo

# Avoid APT interactively requesting to configure tzdata.
RUN DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata

# Add standard user to sudoers group.
RUN usermod -a -G sudo ubuntu

# Allow sudo commands with no password.
RUN printf "%%sudo ALL=(ALL) NOPASSWD:ALL\n" >> /etc/sudoers

# Fix current sudo bug for containers.
# https://github.com/sudo-project/sudo/issues/42
RUN echo "Set disable_coredump false" >> /etc/sudo.conf

ENV HOME=/home/ubuntu USER=ubuntu
USER ubuntu

# Install Bootware.
RUN curl -LSfs https://raw.githubusercontent.com/wolfgangwazzlestrauss/bootware/master/install.sh | bash

# Install dependencies for Bootware.
RUN bootware setup

# Create bootware project directory.
RUN mkdir $HOME/bootware
WORKDIR $HOME/bootware

# Copy bootware project files.
COPY group_vars/ ./group_vars/
COPY main.yaml ./
COPY roles/ ./roles/

ARG tags

# Run Bootware bootstrapping.
RUN bootware bootstrap --dev --no-passwd ${tags:+--tags $tags}

# Copy bootware script files for testing.
COPY scripts/ ./scripts/

# Set Bash as default shell.
SHELL ["/bin/bash", "-c"]

# Test installed binaries for roles.
RUN source "${HOME}/.bashrc" \
    && node scripts/test_roles.js "Linux" "${TARGETARCH}" "${tags:+--tags $tags}"
