---
- name: Install Bat for FreeBSD
  become: true
  community.general.pkgng:
    name: bat
  tags:
    - install
  when:
    - system_install
    - ansible_facts.system == "FreeBSD"

- name: Install Bat for Linux
  ansible.builtin.package:
    name: bat
  become: true
  ignore_errors: true
  register: bat_linux
  tags:
    - install
  when:
    - system_install
    - ansible_facts.system == "Linux"

- name: Get latest Bat version for Linux
  ansible.builtin.uri:
    method: GET
    return_content: true
    url: https://formulae.brew.sh/api/formula/bat.json
  register: bat_formula
  tags:
    - install
  when:
    - ansible_facts.system == "Linux"
    - system_libc == "gnu" or system_architecture == 'amd64'
    - not system_install or bat_linux is failed

- name: Create Bat temporary directory for Linux
  ansible.builtin.tempfile:
    state: directory
  register: bat_temp
  tags:
    - install
  when:
    - ansible_facts.system == "Linux"
    - system_libc == "gnu" or system_architecture == 'amd64'
    - not system_install or bat_linux is failed

- name: Download Bat for Linux
  ansible.builtin.unarchive:
    dest: "{{ bat_temp.path }}"
    mode: "777"
    remote_src: true
    src: >-
      https://github.com/sharkdp/bat/releases/download/v{{
      bat_formula.json.versions.stable }}/bat-v{{
      bat_formula.json.versions.stable }}-{{ bat_arch }}-unknown-linux-{{
      system_libc }}.tar.gz
  tags:
    - install
  when:
    - ansible_facts.system == "Linux"
    - system_libc == "gnu" or system_architecture == 'amd64'
    - not system_install or bat_linux is failed

- name: Install Bat for Linux
  ansible.builtin.copy:
    dest: "{{ bin_path }}/bat"
    force: true
    mode: "755"
    remote_src: true
    src: >-
      {{ bat_temp.path }}/bat-v{{ bat_formula.json.versions.stable }}-{{
      bat_arch }}-unknown-linux-{{ system_libc }}/bat
  become: "{{ system_install }}"
  tags:
    - install
  when:
    - ansible_facts.system == "Linux"
    - system_libc == "gnu" or system_architecture == 'amd64'
    - not system_install or bat_linux is failed

- name: Install Bat shell completions for Linux
  ansible.builtin.copy:
    dest: "{{ item.dest }}"
    force: true
    mode: "644"
    remote_src: true
    src: >-
      {{ bat_temp.path }}/bat-v{{ bat_formula.json.versions.stable }}-{{
      bat_arch }}-unknown-linux-{{ system_libc }}/autocomplete/bat.{{ item.shell
      }}
  become: "{{ system_install }}"
  loop:
    - dest: "{{ bash_completion }}/bat"
      shell: bash
    - dest: "{{ fish_completion }}/bat.fish"
      shell: fish
  tags:
    - completion
    - install
  when:
    - ansible_facts.system == "Linux"
    - system_libc == "gnu" or system_architecture == 'amd64'
    - not system_install or bat_linux is failed

# Debian Bat package installs Bat as command "batcat" since another package
# installs the command "bat".
- name: Make Bat symlink for Debian
  ansible.builtin.file:
    src: /usr/bin/batcat
    dest: "{{ bin_path }}/bat"
    force: true
    mode: "755"
    state: link
  become: "{{ system_install }}"
  tags:
    - install
  when:
    - system_install
    - system_pkg_mgr == "apt"
    - bat_linux is success

- name: Install Bat for MacOS
  become: "{{ system_install }}"
  become_user: "{{ brew_user }}"
  community.general.homebrew:
    name: bat
  tags:
    - install
  when: ansible_facts.system == "Darwin"

- name: Install Bat for Windows
  community.windows.win_scoop:
    global: "{{ system_install }}"
    name: bat
  tags:
    - install
  when: ansible_facts.system == "Win32NT"

- name: Create Bat settings directory for Unix
  ansible.builtin.file:
    dest: "{{ user_home }}/.config/bat"
    group: "{{ group_id }}"
    mode: "755"
    owner: "{{ user_id }}"
    state: directory
  become: "{{ system_install }}"
  tags:
    - config
  when: ansible_facts.system != "Win32NT"

- name: Copy Bat settings file for Unix
  ansible.builtin.copy:
    dest: "{{ user_home }}/.config/bat/config"
    force: true
    group: "{{ group_id }}"
    mode: "644"
    owner: "{{ user_id }}"
    src: config
  become: "{{ system_install }}"
  tags:
    - config
  when: ansible_facts.system != "Win32NT"

- name: Create Bat settings directory for Windows
  ansible.windows.win_file:
    path: "{{ user_home }}\\AppData\\Roaming\\bat"
    state: directory
  tags:
    - config
  when: ansible_facts.system == "Win32NT"

- name: Copy Bat settings file for Windows
  ansible.windows.win_copy:
    dest: "{{ user_home }}\\AppData\\Roaming\\bat\\config"
    force: true
    src: config
  tags:
    - config
  when: ansible_facts.system == "Win32NT"

- name: Override Scoop custom Bat configuration path for Windows
  ansible.windows.win_environment:
    level: user
    name: BAT_CONFIG_PATH
    value: "{{ user_home }}\\AppData\\Roaming\\bat\\config"
  tags:
    - config
  when: ansible_facts.system == "Win32NT"

- name: Set owner of Bat files for Windows
  ansible.windows.win_owner:
    path: "{{ user_home }}\\AppData\\Roaming\\bat"
    recurse: true
    user: "{{ user_id }}"
  tags:
    - config
  when: ansible_facts.system == "Win32NT"

- name: Remove Bat temporary directory for Linux
  ansible.builtin.file:
    path: "{{ bat_temp.path }}"
    state: absent
  tags:
    - install
  when:
    - ansible_facts.system == "Linux"
    - system_libc == "gnu" or system_architecture == 'amd64'
    - not system_install or bat_linux is failed
