---
- name: Install LocalSend for Linux
  become: true
  community.general.flatpak:
    name: org.localsend.localsend_app
  tags:
    - install
  when:
    - system_install
    - ansible_facts.system == "Linux"

- name: Install LocalSend for MacOS
  become: "{{ system_install }}"
  become_user: "{{ brew_user }}"
  community.general.homebrew_cask:
    accept_external_apps: true
    name: localsend
    state: present
  tags:
    - install
  when: ansible_facts.system == "Darwin"

- name: Install LocalSend for Windows
  community.windows.win_scoop:
    global: "{{ system_install }}"
    name: localsend
  tags:
    - install
  when: ansible_facts.system == "Win32NT"
