---
- name: Download AMD GPG key for Debian
  ansible.builtin.get_url:
    dest: "{{ docker_temp.path }}/amd.gpg"
    mode: "640"
    url: https://stable.repo.amd.com/rocm/gpg/packages.gpg
  become: true
  tags:
    - install
  when: system_pkg_mgr == "apt" and system_architecture == "amd64"

- name: Add AMD GPG key for Debian
  ansible.builtin.command:
    cmd: >-
      gpg --batch --dearmor --yes --output /usr/share/keyrings/amd.gpg {{
      docker_temp.path }}/amd.gpg
    creates: /usr/share/keyrings/amd.gpg
  become: true
  tags:
    - install
  when: system_pkg_mgr == "apt" and system_architecture == "amd64"

- name: Add AMD GPG key for Fedora
  ansible.builtin.rpm_key:
    key: https://stable.repo.amd.com/rocm/gpg/packages.gpg
  become: true
  tags:
    - install
  when: system_pkg_mgr == "dnf" and system_architecture == "amd64"

- name: Add ROCm repository for Debian
  ansible.builtin.copy:
    content: |
      Architectures: amd64
      Components: main
      Enabled: yes
      Signed-By: /etc/apt/keyrings/amd.gpg
      Suites: stable
      Types: deb
      URIs: https://stable.repo.amd.com/rocm/core/packages/debian13/
      X-Repo-Id: amdrocm-stable
    dest: /etc/apt/sources.list.d/amdrocm.sources
    force: true
    mode: "644"
  become: true
  tags:
    - install
  when: system_pkg_mgr == "apt" and system_architecture == "amd64"

- name: Add ROCm repository for Fedora
  ansible.builtin.copy:
    content: |
      [amdrocm]
      baseurl=https://stable.repo.amd.com/rocm/core/packages/rhel10/x86_64
      enabled=1
      gpgcheck=1
      gpgkey=https://stable.repo.amd.com/rocm/gpg/packages.gpg
      name=ROCm 10.0.0
    dest: /etc/yum.repos.d/amdrocm.repo
    force: true
    mode: "644"
  become: true
  tags:
    - install
  when: system_pkg_mgr == "dnf" and system_architecture == "amd64"

- name: Install ROCm toolkit for Linux
  ansible.builtin.package:
    name:
      - amdrocm-core-sdk10.0
    update_cache: true
  become: true
  tags:
    - install
  when: system_pkg_mgr in ["apt", "dnf"] and system_architecture == "amd64"

- name: Add user to GPU groups for Linux
  ansible.builtin.user:
    append: true
    groups:
      - render
      - video
    name: "{{ user_id }}"
  become: true
  tags:
    - install
  when: system_pkg_mgr in ["apt", "dnf"] and system_architecture == "amd64"
