---
- name: Install Presenterm for Linux
  ansible.builtin.package:
    name: presenterm
  become: true
  ignore_errors: true
  register: presenterm_linux
  tags:
    - install
  when:
    - system_install
    - ansible_facts.system == "Linux"

- name: Get latest Presenterm version for Linux
  ansible.builtin.uri:
    method: GET
    return_content: true
    url: https://formulae.brew.sh/api/formula/presenterm.json
  register: presenterm_formula
  tags:
    - install
  when:
    - ansible_facts.system == "Linux"
    - not system_install or presenterm_linux is failed

- name: Create Presenterm temporary directory for Linux
  ansible.builtin.tempfile:
    state: directory
  register: presenterm_temp
  tags:
    - install
  when:
    - ansible_facts.system == "Linux"
    - not system_install or presenterm_linux is failed

- name: Set Presenterm temporary directory permissions for Linux
  ansible.builtin.file:
    mode: "755"
    path: "{{ presenterm_temp.path }}"
    state: directory
  tags:
    - install
  when:
    - ansible_facts.system == "Linux"
    - not system_install or presenterm_linux is failed

- name: Download Presenterm for Linux
  ansible.builtin.unarchive:
    dest: "{{ presenterm_temp.path }}"
    mode: "755"
    remote_src: true
    src: >-
      https://github.com/mfontanini/presenterm/releases/download/v{{
      presenterm_formula.json.versions.stable }}/presenterm-{{
      presenterm_formula.json.versions.stable }}-{{ presenterm_arch
      }}-unknown-linux-{{ presenterm_libc }}.tar.gz
  tags:
    - install
  when:
    - ansible_facts.system == "Linux"
    - not system_install or presenterm_linux is failed

- name: Install Presenterm for Linux
  ansible.builtin.copy:
    dest: "{{ bin_path }}/presenterm"
    force: true
    mode: "755"
    remote_src: true
    src: >-
      {{ presenterm_temp.path }}/presenterm-{{
      presenterm_formula.json.versions.stable }}/presenterm
  become: "{{ system_install }}"
  tags:
    - install
  when:
    - ansible_facts.system == "Linux"
    - not system_install or presenterm_linux is failed

- name: Install Presenterm for MacOS
  become: "{{ system_install }}"
  become_user: "{{ brew_user if system_install else omit }}"
  community.general.homebrew:
    name: presenterm
  tags:
    - install
  when: ansible_facts.system == "Darwin"

- name: Install Presenterm for Windows
  community.windows.win_scoop:
    global: "{{ system_install }}"
    name: presenterm
  tags:
    - install
  when: ansible_facts.system == "Win32NT"

- name: Create Presenterm configuration directory for Linux
  ansible.builtin.file:
    group: "{{ group_id if system_install else omit }}"
    mode: "755"
    owner: "{{ user_id if system_install else omit }}"
    path: "{{ user_home }}/.config/presenterm"
    state: directory
  become: "{{ system_install }}"
  tags:
    - config
  when: ansible_facts.system == "Linux"

- name: Copy Presenterm configuration file for Linux
  ansible.builtin.copy:
    dest: "{{ user_home }}/.config/presenterm/config.yaml"
    force: true
    group: "{{ group_id if system_install else omit }}"
    mode: "644"
    owner: "{{ user_id if system_install else omit }}"
    src: config.yaml
  become: "{{ system_install }}"
  tags:
    - config
  when: ansible_facts.system == "Linux"

- name: Create Presenterm configuration directory for MacOS
  ansible.builtin.file:
    group: "{{ group_id if system_install else omit }}"
    mode: "755"
    owner: "{{ user_id if system_install else omit }}"
    path: "{{ user_home }}/Library/Application Support/presenterm"
    state: directory
  become: "{{ system_install }}"
  tags:
    - config
  when: ansible_facts.system == "Darwin"

- name: Copy Presenterm configuration file for MacOS
  ansible.builtin.copy:
    dest: "{{ user_home }}/Library/Application Support/presenterm/config.yaml"
    force: true
    group: "{{ group_id if system_install else omit }}"
    mode: "644"
    owner: "{{ user_id if system_install else omit }}"
    src: config.yaml
  become: "{{ system_install }}"
  tags:
    - config
  when: ansible_facts.system == "Darwin"

- name: Create Presenterm configuration directory for Windows
  ansible.windows.win_file:
    path: "{{ user_home }}\\AppData\\Roaming\\presenterm\\config"
    state: directory
  tags:
    - config
  when: ansible_facts.system == "Win32NT"

- name: Copy Presenterm configuration file for Windows
  ansible.windows.win_copy:
    dest: "{{ user_home }}\\AppData\\Roaming\\presenterm\\config\\config.yaml"
    force: true
    src: config.yaml
  tags:
    - config
  when: ansible_facts.system == "Win32NT"

- name: Set owner of Presenterm files for Windows
  ansible.windows.win_owner:
    path: "{{ user_home }}\\AppData\\Roaming\\presenterm\\config"
    recurse: true
    user: "{{ user_id }}"
  tags:
    - config
  when: ansible_facts.system == "Win32NT"

- name: Remove Presenterm temporary directory for Linux
  ansible.builtin.file:
    path: "{{ presenterm_temp.path }}"
    state: absent
  tags:
    - install
  when:
    - ansible_facts.system == "Linux"
    - not system_install or presenterm_linux is failed
