# Ansible Galaxy collection metadata file.
#
# For more information, visit
# https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html#collections-galaxy-meta.

---
authors:
  - Macklan Weinstein <macklan.weinstein@gmail.com>
build_ignore:
  - .DS_Store
  - .classpath
  - .dockerignore
  - .editorconfig
  - .github
  - .localized
  - .shellcheckrc
  - .venv
  - PSScriptAnalyzerSettings.psd1
  - Thumbs.db
  - __pycache__
  - doc
  - node_modules
  - package-lock.json
  - package.json
  - pyproject.toml
  - script
  - test
  - tmp
  - uv.lock
dependencies:
  chocolatey.chocolatey: ">=1.1.0"
  community.general: ">=4.0.0"
  community.windows: ">=1.9.0"
description: software installers
documentation: https://scruffaluff.github.io/bootware
homepage: https://github.com/scruffaluff/bootware
issues: https://github.com/scruffaluff/bootware/issues
license:
  - MIT
name: bootware
namespace: scruffaluff
readme: README.md
repository: https://github.com/scruffaluff/bootware
tags:
  - install
  - linux
  - tools
  - windows
version: "0.10.0"
