\" Bootware man page, written in the Troff markup language.
\"
\" For a tutorial on writing man pages in Troff, visit https://liw.fi/manpages.
\" For a man page macro reference, visit https://linux.die.net/man/7/man.

.TH BOOTWARE 1

.SH NAME
bootware \- bootstrap software installations with Ansible

.SH SYNOPSIS
.B bootware
[-h|--help|-v|--version]
.PP
.B bootware
bootstrap [OPTIONS]
.PP
.B bootware
config [OPTIONS]
.PP
.B bootware
roles [OPTIONS]
.PP
.B bootware
setup [OPTIONS]
.PP
.B bootware
update [OPTIONS]
.PP
.B bootware
uninstall [OPTIONS]

.SH DESCRIPTION
.B Bootware
bootstraps software installations with Ansible.

.SH OPTIONS
.TP
.BR \-\-debug
Enable shell debug traces
.TP
.BR \-h ", " \-\-help
Print help information
.TP
.BR \-h ", " \-\-version
Print vesrion information

.SH COMMANDS
Use "bootware -h" or "bootware \-\-help" to get an overview of available
commands.

.SH EXAMPLES
.PP
For specific client examples please see the man page for the specific Bootware
command. For example:

.PP
.RS

.nf
man bootware\-bootstrap

.fi
.RE

.SH ENVIRONMENT

.SH FILES

.SH AUTHOR
Macklan Weinstein <macklan.weinstein@gmail.com>

.SH COPYRIGHT
Copyright © 2021-Present Macklan Weinstein. Bootware is distributed under the
MIT license.

.SH SEE ALSO
Full documentation is available at <https://scruffaluff.github.io/bootware>. 
