# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "generic/ubuntu2204"

  config.vm.provider "virtualbox" do |vb|
    # Do not display the VirtualBox GUI when booting the machine.
    vb.gui = false
    # Customize the amount of memory on the VM in megabytes.
    vb.memory = "4096"
    # To speed up creation of new VMs, create a hidden master VM. All new VMs
    # are created by spinning off a new disk image from the hidden master VM
    # rather than import the base image.
    vb.linked_clone = true
  end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", path: "../../install.sh"

  # Share an additional folder to the guest VM. The first argument is the path
  # on the host to the actual folder. The second argument is the path on the
  # guest to mount the folder. And the optional third argument is a set of
  # non-required options.
  config.vm.synced_folder "../../", "/home/vagrant/bootware", type: "rsync"
end
