---
- name: Install VSCode
  ansible.builtin.import_tasks: install.yaml
  when: system_pkg_mgr != "apk"

- name: Configure VSCode user settings
  ansible.builtin.import_tasks: config.yaml
  when: system_pkg_mgr != "apk"

- name: Apply custom styles to VSCode
  ansible.builtin.import_tasks: style.yaml
  when: vscode_style and system_pkg_mgr != "apk"

- name: Set owner of VSCode files for Windows
  ansible.windows.win_owner:
    path: "{{ user_home }}\\{{ item }}"
    recurse: true
    user: "{{ user_id }}"
  loop:
    - .vscode
    - AppData\Roaming\VSCode
  tags:
    - config
  when: ansible_facts.system == "Win32NT"
