# Amethyst configuration file for tiling windows.
#
# For more information, visit
# https://github.com/ianyh/Amethyst/blob/development/docs/configuration-files.md.

---
cycle-layout:
  mod: mod1
  key: "]"
cycle-layout-backward:
  mod: mod1
  key: "["
# Do not show the layout name when a new layout is selected.
enables-layout-hud: false
# Do not show the layout name when moving to a new space.
enables-layout-hud-on-space-change: false
# Focus next window counter clockwise in current space.
focus-ccw:
  key: j
  mod: mod1
# Focus next window clockwise in current space.
focus-cw:
  key: ";"
  mod: mod1
focus-screen-ccw:
  key: j
  mod: mod3
focus-screen-cw:
  key: ";"
  mod: mod3
hide-menu-bar-icon: false
layouts:
  - tall
  - wide
  - fullscreen
mod1:
  - command
  - shift
mod2:
  - command
  - control
mod3:
  - command
  - control
  - shift
mouse-follows-focus: true
relaunch-amethyst:
  key: r
  mod: mod2
select-fullscreen-layout:
  key: m
  mod: mod1
swap-ccw:
  key: left
  mod: mod1
swap-cw:
  key: right
  mod: mod1
# Move focused window to next monitor counter clockwise.
swap-screen-ccw:
  key: left
  mod: mod3
# Move focused window to next monitor clockwise.
swap-screen-cw:
  key: right
  mod: mod3
# Move focused window to space on the left.
throw-space-left:
  key: left
  mod: mod2
# Move focused window to space on the right.
throw-space-right:
  key: right
  mod: mod2
toggle-float:
  key: f
  mod: mod1
# Turn on or off tiling entirely.
toggle-tiling:
  key: t
  mod: mod3
window-margin-size: 4
window-margins: true

# Disable keybindings.
#
# Amethyst keybindings cannot be disabled directly. Instead they can only be
# reset to an unused keybinding. For more information, visit
# https://github.com/ianyh/Amethyst/issues/1329#issuecomment-1469898303.

# Decrease number of windows in the main pane.
decrease-main:
  key: "!"
  mod: mod4
# Display current layout HUD on each screen.
display-current-layout:
  key: "!"
  mod: mod4
# Expand the main pane on each monitor.
expand-main:
  key: "!"
  mod: mod4
# Move focused window to space 1.
focus-screen-1:
  key: "!"
  mod: mod4
focus-screen-2:
  key: "!"
  mod: mod4
focus-screen-3:
  key: "!"
  mod: mod4
focus-screen-4:
  key: "!"
  mod: mod4
focus-screen-5:
  key: "!"
  mod: mod4
# Increase number of windows in main pane.
increase-main:
  key: "!"
  mod: mod4
focus-main:
  key: "!"
  mod: mod4
# Unused modifier key combination.
mod4:
  - command
  - control
  - option
  - shift
# Rerun current layout algorithm.
reevaluate-windows:
  key: "!"
  mod: mod4
select-column-layout:
  key: "!"
  mod: mod4
select-tall-layout:
  key: "!"
  mod: mod4
select-wide-layout:
  key: "!"
  mod: mod4
shrink-main:
  key: "!"
  mod: mod4
# Swap focused window with the main window.
swap-main:
  key: "!"
  mod: mod4
throw-screen-1:
  key: "!"
  mod: mod4
throw-screen-2:
  key: "!"
  mod: mod4
throw-screen-3:
  key: "!"
  mod: mod4
throw-screen-4:
  key: "!"
  mod: mod4
throw-screen-5:
  key: "!"
  mod: mod4
toggle-focus-follows-mouse:
  key: "!"
  mod: mod4
