# Yazi configuration file for file management.
#
# For more information, visit https://yazi-rs.github.io/docs/configuration/yazi.

[mgr]
ratio = [0, 1, 2]

[open]
append_rules = [{ url = "*", use = "edit" }]
prepend_rules = [
  { mime = "audio/*", use = [
    "sound",
    "reveal",
  ] },
  { mime = "image/*", use = [
    "show",
    "reveal",
  ] },
]

[opener]
edit = [
  { block = true, desc = "$EDITOR", for = "unix", run = '${EDITOR:-vi} %s1' },
  { block = true, desc = "%EDITOR%", for = "windows", run = '%EDITOR% %s1' },
]
show = [
  { block = true, desc = "chafa", for = "unix", run = 'chafa --clear --align center --duration infinite --scale max %s1; clear' },
  { block = true, desc = "chafa", for = "windows", run = 'chafa --clear --align center --duration infinite --scale max %s1; clear' },
  { block = true, desc = "mediainfo", for = "unix", run = 'mediainfo %s1; echo "Press enter to exit"; read _' },
]
sound = [
  { block = true, desc = "mpv", for = "unix", run = 'mpv --no-video %s1; clear' },
  { block = true, desc = "mpv", for = "windows", run = 'mpv --no-video %s1; clear' },
  { block = true, desc = "mediainfo", for = "unix", run = 'mediainfo %s1; echo "Press enter to exit"; read _' },
]

[plugin]
preloaders = []
prepend_fetchers = [
  { group = "git", run = "git", url = "*/" },
  { group = "git", run = "git", url = "*" },
  { group = "mime", prio = "high", run = "mime-ext.local", url = "local://*" },
  { group = "mime", prio = "high", run = "mime-ext.remote", url = "remote://*" },
]
# Previewers edited to use "code" as the fallback option based on
# https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/yazi-default.toml
previewers = [
	{ url = "*/", run = "folder" },
	{ mime = "text/*", run = "code" },
	{ mime = "application/{mbox,javascript,wine-extension-ini}", run = "code" },
	{ mime = "application/{json,ndjson}", run = "json" },
	{ mime = "audio/*", run = "file" },
	{ mime = "image/{avif,hei?,jxl}", run = "magick" },
	{ mime = "image/svg+xml", run = "svg" },
	{ mime = "image/*", run = "image" },
	{ mime = "video/*", run = "video" },
	{ mime = "application/pdf", run = "pdf" },
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", run = "archive" },
	{ mime = "application/{debian*-package,redhat-package-manager,rpm,android.package-archive}", run = "archive" },
	{ mime = "application/{iso9660-image,qemu-disk,ms-wim,apple-diskimage}", run = "archive" },
	{ mime = "application/virtualbox-{vhd,vhdx}", run = "archive" },
	{ mime = "font/*", run = "font" },
	{ mime = "application/ms-opentype", run = "font" },
	{ mime = "inode/empty", run = "empty" },
	{ mime = "vfs/*", run = "vfs" },
	{ mime = "null/*", run = "null" },
	{ run = "archive", url = "*.{AppImage,appimage,img,fat,ext,ext2,ext3,ext4,squashfs,ntfs,hfs,hfsx}" },
	{ run = "file", url = "*.{a,bin,dll,dylib,exe,o,pyc,pyo,so,whl}" },
	{ run = "code", url = "*" },
]

[preview]
max_height = 2160
max_width = 4096

[tasks]
image_bound = [0, 0]
